name: "spidering address of china"

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: "1 15 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: run app
        run: GO111MODULE=off go run spider/go/main.go

      - name: upload json
        uses: actions/upload-artifact@v4.4.0
        with:
          name: "address_json"
          path: json/
          retention-days: 5

      - name: upload sql
        uses: actions/upload-artifact@v4.4.0
        with:
          name: "address_sql"
          path: sql/
          retention-days: 5

